### ISSUE TITLE
How to calculate the TOPS accurately?

### ISSUE THREAD

**Issue by LiuJingBecky** [enyac-group/MaxEVA#2]
you use the difference between two "TLAST" to calculate the "TOPS", is it accurate?

**Comment by endritaka** [comment]
To calculate the average throughput, we need to find the average number of operations per second. Each output port in our design (Cx,z in Fig. 4) generates an output of M*N values every “TLAST”. In the steady state (after first execution), the throughput is calculated as the average of the difference between two “TLAST” times, among all output ports (since they are independent). 

This is the average data rate being produced by the AIE, thus capturing accurately the average (actual) TOPs of the design.
